version: "3.5"

networks:
  default:
    name: kafka-demo

services:
  zookeeper:
    image: confluent/zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  broker-1:
    image: confluent/kafka
    hostname: broker-1
    container_name: broker-1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper